package proyecto3;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Visual extends javax.swing.JFrame {

    list list = new list();

    public Visual() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel Tabla = new DefaultTableModel();
        list.fillTable(tabIn, true);
        list.fillTable(tabTu, false);
        Page1.setVisible(true);
        Page2.setVisible(false);
        Page3.setVisible(false);
        Page4.setVisible(false);
        Page5.setVisible(false);
        select.setVisible(false);

    }

    public void setPage1true() {
        Page1.setVisible(true);
        Page1.setEnabled(true);
    }

    public void setPage1false() {
        Page1.setVisible(false);
        Page1.setEnabled(false);
    }

    public void setPage2true() {
        Page2.setVisible(true);
        Page2.setEnabled(true);
    }

    public void setPage2false() {
        Page2.setVisible(false);
        Page2.setEnabled(false);
    }

    public void setPage3true() {
        Page3.setVisible(true);
        Page3.setEnabled(true);
    }

    public void setPage3false() {
        Page3.setVisible(false);
        Page3.setEnabled(false);
    }

    public void setPage4true() {
        Page4.setVisible(true);
        Page4.setEnabled(true);
    }

    public void setPage4false() {
        Page4.setVisible(false);
        Page4.setEnabled(false);
    }

    public void setPage5true() {
        Page5.setVisible(true);
        Page5.setEnabled(true);
    }

    public void setPage5false() {
        Page5.setVisible(false);
        Page5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Plant = new javax.swing.JPanel();
        Page1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Page2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idTu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        naTu = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabTu = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        Page3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        i = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        w = new javax.swing.JSpinner();
        s = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Pos = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        a = new javax.swing.JSlider();
        jLabel27 = new javax.swing.JLabel();
        m = new javax.swing.JComboBox<>();
        Page4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabIn = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        delAcu = new javax.swing.JRadioButton();
        delCh = new javax.swing.JRadioButton();
        delTiu = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Page5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AReport = new javax.swing.JTextArea();
        lowSize = new javax.swing.JButton();
        LowWeight = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        select = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        seleCh = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        setPage1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        setPage2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        setPage3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        setPage4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        setPage5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Exit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Plant.setBackground(new java.awt.Color(255, 255, 255));
        Plant.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Page1.setBackground(new java.awt.Color(204, 204, 204));
        Page1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sistema de administracion de datos de niños bajos en peso");
        Page1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 380, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Julio Eliecer Nova Estrada");
        Page1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 170, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Jorge Eliecer Oviedo Vanegas");
        Page1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 200, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Programacion 2 - Proyecto 3");
        Page1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 190, -1));

        Plant.add(Page1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 630));

        Page2.setBackground(new java.awt.Color(204, 204, 204));
        Page2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Ingrese los datos del acudiente:");
        Page2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, 214, 26));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Id:");
        Page2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 66, -1, -1));

        idTu.setBackground(new java.awt.Color(204, 204, 204));
        idTu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        idTu.setForeground(new java.awt.Color(0, 0, 0));
        idTu.setBorder(null);
        Page2.add(idTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 20));
        Page2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 10));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre:");
        Page2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        naTu.setBackground(new java.awt.Color(204, 204, 204));
        naTu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        naTu.setForeground(new java.awt.Color(0, 0, 0));
        naTu.setBorder(null);
        Page2.add(naTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 20));
        Page2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 12));

        tabTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabTu);

        Page2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 520, 570));

        jButton5.setText("Añadir tutor");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Page2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 130, 30));

        Plant.add(Page2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 630));

        Page3.setBackground(new java.awt.Color(204, 204, 204));
        Page3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Registro civil");
        Page3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Ingrese los datos del infante:");
        Page3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        i.setBackground(new java.awt.Color(204, 204, 204));
        i.setForeground(new java.awt.Color(0, 0, 0));
        i.setBorder(null);
        Page3.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 20));
        Page3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, 10));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nombre:");
        Page3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        n.setBackground(new java.awt.Color(204, 204, 204));
        n.setForeground(new java.awt.Color(0, 0, 0));
        n.setBorder(null);
        Page3.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 140, 20));
        Page3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 170, 10));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Altura (cm):");
        Page3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Peso (Kg):");
        Page3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acudientes" }));
        jComboBox1.setBorder(null);
        Page3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 200, 30));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Seleccionar acudiente:");
        Page3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 160, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Seleccionar municipio:");
        Page3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        w.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        w.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(30.0f), Float.valueOf(5.0f), Float.valueOf(120.0f), Float.valueOf(0.1f)));
        w.setBorder(null);
        Page3.add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 120, 20));

        s.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        s.setModel(new javax.swing.SpinnerNumberModel(100, 15, 220, 1));
        s.setBorder(null);
        Page3.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, 20));

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("añadir despues de");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Page3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 150, 30));

        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setText("Añadir al final");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Page3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 150, 30));

        jButton4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton4.setText("Añadir al inicio");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Page3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 150, 30));

        Pos.setBackground(new java.awt.Color(204, 204, 204));
        Pos.setForeground(new java.awt.Color(0, 0, 0));
        Pos.setBorder(null);
        Page3.add(Pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 140, 20));
        Page3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 170, 10));

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Posición:");
        Page3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 70, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Edad:");
        Page3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        a.setBackground(new java.awt.Color(204, 204, 204));
        a.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        a.setForeground(new java.awt.Color(0, 0, 0));
        a.setMajorTickSpacing(1);
        a.setMaximum(6);
        a.setMinimum(1);
        a.setMinorTickSpacing(1);
        a.setPaintTicks(true);
        a.setValue(1);
        a.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aStateChanged(evt);
            }
        });
        Page3.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("1");
        Page3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 50, 20));

        m.setBackground(new java.awt.Color(204, 204, 204));
        m.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        m.setForeground(new java.awt.Color(0, 0, 0));
        m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipios", "Monteria", "Sahagún", "Lorica" }));
        m.setBorder(null);
        Page3.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 160, -1));

        Plant.add(Page3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 630));

        Page4.setBackground(new java.awt.Color(204, 204, 204));
        Page4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabIn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabIn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Altura", "Peso", "Tutor", "Municipio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabIn);

        Page4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 940, 390));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Informacion del infante:");
        Page4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Buscar Id:");
        Page4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));
        Page4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 170, 10));

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jTextField8.setBorder(null);
        Page4.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 140, 20));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Page4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 100, -1));

        buttonGroup1.add(delAcu);
        delAcu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        delAcu.setText("Eliminar acudiente");
        delAcu.setBorder(null);
        delAcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAcuActionPerformed(evt);
            }
        });
        Page4.add(delAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 25));

        buttonGroup1.add(delCh);
        delCh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        delCh.setText("Eliminar infante");
        delCh.setBorder(null);
        Page4.add(delCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 25));

        delTiu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        delTiu.setBorder(null);
        Page4.add(delTiu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 120, 25));

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Page4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 90, -1));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Acudiente");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        Page4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Infante");
        Page4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        Plant.add(Page4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 630));

        Page5.setBackground(new java.awt.Color(204, 204, 204));
        Page5.setForeground(new java.awt.Color(0, 0, 0));
        Page5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Reporte:");
        Page5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        AReport.setColumns(20);
        AReport.setRows(5);
        jScrollPane3.setViewportView(AReport);

        Page5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 750, 440));

        lowSize.setText("Niños bajos en estatura");
        lowSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowSizeActionPerformed(evt);
            }
        });
        Page5.add(lowSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, 30));

        LowWeight.setText("Niños bajos en peso");
        LowWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowWeightActionPerformed(evt);
            }
        });
        Page5.add(LowWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 170, 30));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Mostrar reporte de:");
        Page5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, -1));

        jButton8.setLabel("Todos los niños");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Page5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 170, 30));

        jButton9.setLabel("Exportar informe");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Page5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 150, 30));

        Plant.add(Page5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 630));

        select.setBackground(new java.awt.Color(153, 153, 153));
        select.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton7.setText("Mostrar");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        select.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 60, 30));

        seleCh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        seleCh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantes" }));
        seleCh.setBorder(null);
        select.add(seleCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 170, 30));

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel25.setText("Seleccione el infante");
        select.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        Plant.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 340, 150));

        setPage1.setBackground(new java.awt.Color(204, 204, 204));
        setPage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPage1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Inicio");

        javax.swing.GroupLayout setPage1Layout = new javax.swing.GroupLayout(setPage1);
        setPage1.setLayout(setPage1Layout);
        setPage1Layout.setHorizontalGroup(
            setPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        setPage1Layout.setVerticalGroup(
            setPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Plant.add(setPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        setPage2.setBackground(new java.awt.Color(153, 153, 153));
        setPage2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPage2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Añadir acudiente");

        javax.swing.GroupLayout setPage2Layout = new javax.swing.GroupLayout(setPage2);
        setPage2.setLayout(setPage2Layout);
        setPage2Layout.setHorizontalGroup(
            setPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setPage2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        setPage2Layout.setVerticalGroup(
            setPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setPage2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Plant.add(setPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 120, 40));

        setPage3.setBackground(new java.awt.Color(153, 153, 153));
        setPage3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPage3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Añadir infante");

        javax.swing.GroupLayout setPage3Layout = new javax.swing.GroupLayout(setPage3);
        setPage3.setLayout(setPage3Layout);
        setPage3Layout.setHorizontalGroup(
            setPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPage3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        setPage3Layout.setVerticalGroup(
            setPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        Plant.add(setPage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 120, 40));

        setPage4.setBackground(new java.awt.Color(153, 153, 153));
        setPage4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPage4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ver tabla");

        javax.swing.GroupLayout setPage4Layout = new javax.swing.GroupLayout(setPage4);
        setPage4.setLayout(setPage4Layout);
        setPage4Layout.setHorizontalGroup(
            setPage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPage4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        setPage4Layout.setVerticalGroup(
            setPage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        Plant.add(setPage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 120, 40));

        setPage5.setBackground(new java.awt.Color(153, 153, 153));
        setPage5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPage5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPage5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Reporte");

        javax.swing.GroupLayout setPage5Layout = new javax.swing.GroupLayout(setPage5);
        setPage5.setLayout(setPage5Layout);
        setPage5Layout.setHorizontalGroup(
            setPage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setPage5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        setPage5Layout.setVerticalGroup(
            setPage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        Plant.add(setPage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 120, 40));

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setForeground(new java.awt.Color(204, 204, 204));
        Exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("   X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        Exit.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        Plant.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Plant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Plant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void setPage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPage1MouseClicked
        setPage2false();
        setPage3false();
        setPage4false();
        setPage5false();
        setPage1true();
        setPage1.setBackground(new Color(204, 204, 204));
        setPage2.setBackground(new Color(153, 153, 153));
        setPage3.setBackground(new Color(153, 153, 153));
        setPage4.setBackground(new Color(153, 153, 153));
        setPage5.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_setPage1MouseClicked

    private void setPage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPage2MouseClicked
        setPage1false();
        setPage3false();
        setPage4false();
        setPage5false();
        setPage2true();
        setPage2.setBackground(new Color(204, 204, 204));
        setPage1.setBackground(new Color(153, 153, 153));
        setPage3.setBackground(new Color(153, 153, 153));
        setPage4.setBackground(new Color(153, 153, 153));
        setPage5.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_setPage2MouseClicked

    private void setPage3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPage3MouseClicked
        setPage1false();
        setPage2false();
        setPage4false();
        setPage5false();
        setPage3true();
        setPage3.setBackground(new Color(204, 204, 204));
        setPage1.setBackground(new Color(153, 153, 153));
        setPage2.setBackground(new Color(153, 153, 153));
        setPage4.setBackground(new Color(153, 153, 153));
        setPage5.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_setPage3MouseClicked

    private void setPage4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPage4MouseClicked
        setPage1false();
        setPage2false();
        setPage3false();
        setPage5false();
        setPage4true();
        setPage4.setBackground(new Color(204, 204, 204));
        setPage1.setBackground(new Color(153, 153, 153));
        setPage2.setBackground(new Color(153, 153, 153));
        setPage3.setBackground(new Color(153, 153, 153));
        setPage5.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_setPage4MouseClicked

    private void setPage5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPage5MouseClicked
        setPage1false();
        setPage2false();
        setPage3false();
        setPage4false();
        setPage5true();
        setPage5.setBackground(new Color(204, 204, 204));
        setPage1.setBackground(new Color(153, 153, 153));
        setPage2.setBackground(new Color(153, 153, 153));
        setPage3.setBackground(new Color(153, 153, 153));
        setPage4.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_setPage5MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        list.addCab(i, n, s, w, m, a, jComboBox1);
        list.fillTable(tabIn, true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        list.addChildToEnd(i, n, s, w, m, a, jComboBox1);
        list.fillTable(tabIn, true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        list.addIn(i, n, s, w, jComboBox1, m, a, Integer.parseInt(Pos.getText()));
        list.fillTable(tabIn, true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        list.addTutorToEnd(idTu, naTu);
        list.actJCBtutor(jComboBox1);
        list.fillTable(tabTu, false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void delAcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAcuActionPerformed

    }//GEN-LAST:event_delAcuActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (delAcu.isSelected() && delCh.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Seleccione si quiere eliminar un acudiente o un infante");
            return;
        }
        if (delAcu.isSelected()) {
            list.DeleteTutor(delTiu.getText());
        }
        if (delCh.isSelected()) {
            list.DeleteChild(delTiu.getText());
        }
        list.fillTable(tabIn, true);
        list.fillTable(tabTu, false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        JOptionPane.showMessageDialog(null, list.getDatos(seleCh.getSelectedItem().toString()));
        select.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jRadioButton2.isSelected() && jRadioButton1.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Seleccione si desea buscar por la id del tutor o del infante");
            return;
        }
        if (jRadioButton1.isSelected()) {
            list.searchByTutorId(jTextField8.getText(), seleCh, select);
            return;
        }
        if (jRadioButton2.isSelected()) {
            list.getDatos(jTextField8.getText());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void aStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aStateChanged
        jLabel27.setText("" + a.getValue());
    }//GEN-LAST:event_aStateChanged

    private void lowSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowSizeActionPerformed
        AReport.setText("En el municipio de Monteria hay: " + list.lowSizeByCity("Monteria") + " bajos en estatura\n"
                + "En el municipio de Sahagún hay: " + list.lowSizeByCity("Sahagún") + " bajos en estatura\n"
                + "En el municipio de Lorica hay: " + list.lowSizeByCity("Lorica") + " bajos en estatura\n");
    }//GEN-LAST:event_lowSizeActionPerformed

    private void LowWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowWeightActionPerformed
        AReport.setText("");
        list.reportLowWeight("Monteria", AReport);
        list.reportLowWeight("Sahagún", AReport);
        list.reportLowWeight("Lorica", AReport);
    }//GEN-LAST:event_LowWeightActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        AReport.setText("");
        list.reportAll("Monteria", AReport);
        list.reportAll("Sahagún", AReport);
        list.reportAll("Lorica", AReport);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        System.out.println(System.getProperty("user.home"));
        try {
            list.txt();
            JOptionPane.showMessageDialog(null, "Archivo creado en el directorio: "+System.getProperty("user.home")+ "\\Documents\\");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AReport;
    private javax.swing.JPanel Exit;
    private javax.swing.JButton LowWeight;
    private javax.swing.JPanel Page1;
    private javax.swing.JPanel Page2;
    private javax.swing.JPanel Page3;
    private javax.swing.JPanel Page4;
    private javax.swing.JPanel Page5;
    private javax.swing.JPanel Plant;
    private javax.swing.JTextField Pos;
    private javax.swing.JSlider a;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton delAcu;
    private javax.swing.JRadioButton delCh;
    private javax.swing.JTextField delTiu;
    private javax.swing.JTextField i;
    private javax.swing.JTextField idTu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton lowSize;
    private javax.swing.JComboBox<String> m;
    private javax.swing.JTextField n;
    private javax.swing.JTextField naTu;
    private javax.swing.JSpinner s;
    private javax.swing.JComboBox<String> seleCh;
    private javax.swing.JPanel select;
    private javax.swing.JPanel setPage1;
    private javax.swing.JPanel setPage2;
    private javax.swing.JPanel setPage3;
    private javax.swing.JPanel setPage4;
    private javax.swing.JPanel setPage5;
    private javax.swing.JTable tabIn;
    private javax.swing.JTable tabTu;
    private javax.swing.JSpinner w;
    // End of variables declaration//GEN-END:variables
}
